### ISSUE TITLE
katana-workspace tries to overwrite /usr/bin/systemsettings

### ISSUE THREAD

**Issue by MrReplikant** [fluxer/katana-debian#1]
Hello,

I have attempted to use Katana in a live-build system, and it keeps throwing the following error: 

dpkg: error processing archive /var/cache/apt/archives/katana-workspace_4.23.0_a
md64.deb (--unpack):
 trying to overwrite '/usr/bin/systemsettings', which is also in package systems
ettings 4:5.27.5-2
Errors were encountered while processing:
 /var/cache/apt/archives/katana-workspace_4.23.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

It appears that it is conflicting with the systemsettings package from KDE 5. Thought I would bring this to your immediate attention. 

Edit: This is a Debian bookworm system, standard systemd setup, so not using sysvinit or anything. 

Edit number 2: Apparently it conflicts with more than one package
dpkg: error processing archive /mirror/mirror/ftp.us.debian.org/debian/pool/main/k/kglobalaccel/libkf5globalaccel-data_5.
103.0-1_all.deb (--unpack):
 trying to overwrite '/usr/share/dbus-1/services/org.kde.kglobalaccel.service', which is also in package katana-workspace
 4.23.0
Errors were encountered while processing:
 /mirror/mirror/ftp.us.debian.org/debian/pool/main/k/kglobalaccel/libkf5globalaccel-data_5.103.0-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

These all have to do with the dependencies of calamares and calamares-settings-debian. Perhaps the "Provides:" portion of the control file needs to be amended to include these packages?

**Comment by fluxer** [comment]
Hi,

already explained at https://github.com/fluxer/katana/issues/37.

**Comment by fluxer** [comment]
Oh, and read the [wiki](https://github.com/fluxer/katana/wiki/Building-and-installing) page about building and installing.
